language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2

script: "bundle exec rspec"

addons:
  postgresql: "9.4"

services:
  - mysql
  - postgresql

before_script:
  - mysql -e 'create database migrate_test;'
  - psql -c 'create database migrate_test;' -U postgres
  - psql -c 'CREATE SCHEMA IF NOT EXISTS public;' -U postgres
  - psql -c 'SET search_path = public;' -U postgres
